FROM alpine
LABEL org.opencontainers.image.source=https://github.com/argotorg/solidity
LABEL maintainer="Solidity Team <solidity@argot.org>"

COPY upload/solc-static-linux /usr/local/bin/solc
ENTRYPOINT ["/usr/local/bin/solc"]
