name: macOS build
on: [push, pull_request]

jobs:
  build:
    runs-on: b_win

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show workspace path
        run: |
          echo "Current path: $PWD"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls -la

      - name: Run build script
        shell: bash
        run: |
          WINPATH=$(cygpath -w "$(pwd)/.circleci/build_win.ps1")
          powershell.exe -ExecutionPolicy Bypass -File "$WINPATH"