name: macOS build
on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare deps
        shell: bash
        run: powershell.exe scripts/install_deps.ps1

      - name: Run build script
        shell: bash
        run: powershell.exe .circleci/build_win.ps1