name: test aws
on:
  push:
    branches:
      - develop

jobs:
  test_aws:
    runs-on: [ self-hosted, macOS ]

    steps:
      - name: test aws
        shell: zsh -el {0}
        run: |
          aws --version